name: derip2-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python 3.12
  - pip
  - pip:
      - biopython
      - biopython
      - click
      - hatch
      - isort
      - matplotlib
      - numpy
      - numpydoc-validation
      - pre-commit
      - pytest
      - ruff
      - tqdm
