"""The HTML page shell shared by the deRIP2 reports."""

from html import escape

#: Footer shown on every report.
FOOTER = (
    'Generated by deRIP2. Figures are inline SVG and render on their own light '
    'surface so the colourblind-safe palette holds.'
)


def render_page(title, subtitle, body, *, css, scripts=''):
    """
    Wrap report content in a complete, self-contained HTML document.

    Parameters
    ----------
    title : str
        Page title and ``<h1>`` heading (escaped here).
    subtitle : str
        Line shown under the heading, already HTML (not escaped), e.g.
        ``'12 sequences &times; 300 columns'``.
    body : str
        The report sections, already HTML.
    css : str
        Stylesheet text placed in the single ``<style>`` element.
    scripts : str, optional
        Trailing markup (``<script>`` elements and any hidden helpers such as a
        modal) placed after the footer, inside ``<main>``.

    Returns
    -------
    str
        The full document, from ``<!doctype html>`` to ``</html>``.
    """
    heading = escape(title)
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f'<title>{heading}</title><style>{css}</style></head><body><main>'
        f'<header class="masthead"><h1>{heading}</h1>'
        f'<p class="sub">{subtitle}</p></header>'
        f'{body}'
        f'<footer>{FOOTER}</footer>'
        f'{scripts}'
        '</main></body></html>'
    )
