
name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]  # Test with Python 3.8 to the latest available version

    steps:
      # Checkout the latest commit associated with the PR
      - uses: actions/checkout@v4

      - name: Debug matrix value
        run: echo "Python version is ${{ matrix.python-version }}"

      # Set up Python based on the matrix version
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies, including test dependencies from pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'  # Install all dependencies, including test-specific ones

      # Run pytest on the specified directory
      - name: Test with pytest
        run: |
          pytest --cov=derip2 --cov-branch --cov-report=xml

      # Upload coverage report to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Adamtaranto/deRIP2
